# models/vit/config/vit_config.yaml
model:
  type: "vit"
  params:
    img_size: 224
    patch_size: 16
    in_channels: 3
    num_classes: 1
    embed_dim: 768
    depth: 12
    num_heads: 12
    mlp_ratio: 4.0
    dropout: 0.1
    attn_dropout: 0.0
    classifier: "token"   # "token" or "gap"