# models/swin/config/swin_config.yaml
model:
  type: "swin"
  params:
    img_size: 224
    patch_size: 4
    in_channels: 3
    num_classes: 1
    embed_dim: 96
    depths: [2, 2, 6, 2]
    num_heads: [3, 6, 12, 24]
    window_size: 7
    mlp_ratio: 4.0
    dropout: 0.1
    attn_dropout: 0.0